spring.application.name=saude
# Configurações do Banco de Dados H2 (Para rodar localmente sem instalar nada)
spring.datasource.url=jdbc:h2:mem:saudedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Configurações do seu Bot do Telegram
telegram.bot.username=msaude_bot
telegram.bot.token=8807249399:AAGprU2XTyIXwVEusouzE9V3_eBtrQDhzB0